# Use root/example as user/password credentials
version: '3.1'

services:

  myMongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      HTTPINTERFACE: true

  myMongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017

  myFlaskApp:
    image: my_flask_image
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./MonAppliFlask.py:/datafile/MonAppliFlask.py
    entrypoint: ['python', '-m','/datafile/MonAppliFlask.py']